# organization name, it's used to get github repo url, also in page title
name: jshttp

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       UXCore Badgeboard
description: project status at a glance
keywords:    UXCore, badgeboard, repo-utils

# list of projects, this will be sorted by name;
# every package is either string or object
projects:
 - uxcore-alert
 - uxcore-button
 - uxcore-calendar
 - uxcore-carousel
 - uxcore-checkbox-group
 - uxcore-collapse
 - uxcore-const
 - uxcore-crumb
 - uxcore-dialog
 - uxcore-dropdown
 - uxcore-employee-search
 - uxcore-form
 - uxcore-ganttchart
 - uxcore-grid
 - uxcore-hovercard
 - uxcore-layout
 - uxcore-mention
 - uxcore-menu
 - uxcore-message
 - uxcore-multi-select
 - uxcore-pagination
 - uxcore-pickable
 - uxcore-primary-nav
 - uxcore-progress
 - uxcore-radiogroup
 - uxcore-select2
 - uxcore-steps
 - uxcore-table
 - uxcore-tabs
 - uxcore-timeline
 - uxcore-tinymce
 - uxcore-tooltip
 - uxcore-totop
 - uxcore-transfer
 - uxcore-tree
 - uxcore-uploader
 - uxcore-validator

# list of maintainers, this won't be sorted
maintainers:
 - name:    Guang Hong
   github:  macisi       # github account, required: we link to it
   npm:             # npm account, required to determine lead maintainer
   twitter:  # twitter account, optional
   gittip:     # gittub badge, optional
   email:   macisi528@gmail.com

 - name:    Zhou Quan
   github:  majorye
   npm:     
   twitter: 
   gittip:  
   email:   major.yezhouquan@gmail.com

   # if gravatar is attached to an email different from specified above,
   # add md5 of it here:
   # avatar:  6e33cc0412b61cc01daac23c8989003c

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
